# Generated by Django 5.0.7 on 2024-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='body',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
