# Generated by Django 5.0.7 on 2024-08-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_chapter_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
