# Generated by Django 5.0.7 on 2024-08-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_alter_story_options_chapter_user_story_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='story',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='story',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
