# Generated by Django 5.1 on 2024-08-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_chapter_added_date_alter_chapter_update_date_and_more'),
        ('tags', '0004_remove_tag_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
