# Generated by Django 5.1 on 2024-08-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_chapter_added_date_alter_chapter_update_date_and_more'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='story.story'),
            preserve_default=False,
        ),
    ]
