# Generated by Django 5.1 on 2024-08-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_chapter_added_date_alter_chapter_update_date_and_more'),
        ('tags', '0002_tag_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='story',
        ),
        migrations.AddField(
            model_name='tag',
            name='story',
            field=models.ManyToManyField(to='story.story'),
        ),
    ]
