# Generated by Django 5.1 on 2024-08-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_remove_tag_story_tag_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='story',
        ),
    ]
